### PR TITLE
Add me too. Great initiative by the developer <3

### PR DESCRIPTION
**Pull request by ani4aniket**
Thanks 😄

### CODE REVIEW

**Comment by Korusuke** [comment]
Thanks @ani4aniket for the image compressor action!

**Comment by Korusuke** [comment]
Hey @ani4aniket, there is some issue with main.yml, it would be great if you can have a look at that.

**Comment by ani4aniket** [comment]
@Korusuke I am working on it bro, will commit soon

**Comment by Korusuke** [comment]
Sounds great!

**Pull request merged**
